name: Performance Tests
on:
  push:
    branches: [main, master]
    paths:
      - performance-tests/**
      - .github/workflows/performance.yml
  pull_request:
    branches: [main, master]
    paths:
      - performance-tests/**
      - .github/workflows/performance.yml
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd performance-tests
          npm install
      - name: Install k6
        run: |
          sudo gpg -k || sudo apt install gnupg -y
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6 -y
      - name: Run Performance tests
        run: |
          cd performance-tests
          npm run test:performance:ci
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: k6-results
          path: performance-tests/k6-results.json
          retention-days: 30
