name: Performance Tests
on:
  push:
    branches: [main, master]
    paths:
      - 'tests/performance/**'
      - .github/workflows/performance.yml
  pull_request:
    branches: [main, master]
    paths:
      - 'tests/performance/**'
      - .github/workflows/performance.yml
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm install
      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Run Performance tests
        run: |
          npm run test:performance
      - name: Generate k6 results
        run: |
          mkdir -p k6-results
          mv k6-results.json k6-results/
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: k6-results
          path: k6-results/
          retention-days: 30
